owner: lactobionicAcid
repo: PCL-Homepage-Status

sites:
  - name: Minecraft 新闻
    url: https://mcnews.meloong.com
    headers: 
      - "User-Agent: PCL2/0.0.0.0 Mozilla/5.0 AppleWebKit/537.36 Chrome/63.0.3239.132 Safari/537.36"
      - "Referer: http://000.pcl2.server/"

  - name: 每日整合包推荐
    url: https://pclsub.sodamc.com/
    headers: 
      - "User-Agent: PCL2/0.0.0.0 Mozilla/5.0 AppleWebKit/537.36 Chrome/63.0.3239.132 Safari/537.36"
      - "Referer: http://000.pcl2.server/"

  - name: Minecraft 皮肤推荐
    url: https://forgepixel.com/pcl_sub_file
    headers: 
      - "User-Agent: PCL2/0.0.0.0 Mozilla/5.0 AppleWebKit/537.36 Chrome/63.0.3239.132 Safari/537.36"
      - "Referer: http://000.pcl2.server/"

  - name: OpenBMCLAPI 仪表盘 Lite
    url: https://pcl-bmcl.milu.ink/
    headers: 
      - "User-Agent: PCL2/0.0.0.0 Mozilla/5.0 AppleWebKit/537.36 Chrome/63.0.3239.132 Safari/537.36"
      - "Referer: http://000.pcl2.server/"

  - name: PCL 新功能说明书
    url: https://raw.gitcode.com/WForst-Breeze/WhatsNewPCL/raw/main/Custom.xaml
    headers: 
      - "User-Agent: PCL2/0.0.0.0 Mozilla/5.0 AppleWebKit/537.36 Chrome/63.0.3239.132 Safari/537.36"
      - "Referer: http://000.pcl2.server/"

  - name: 杂志主页
    url: http://118.195.192.193:26995/d/magazine-homepage-pcl/Custom.xaml
    headers: 
      - "User-Agent: PCL2/0.0.0.0 Mozilla/5.0 AppleWebKit/537.36 Chrome/63.0.3239.132 Safari/537.36"
      - "Referer: http://000.pcl2.server/"

  - name: PCL GitHub 仪表盘
    url: https://ddf.pcl-community.top/Custom.xaml
    headers: 
      - "User-Agent: PCL2/0.0.0.0 Mozilla/5.0 AppleWebKit/537.36 Chrome/63.0.3239.132 Safari/537.36"
      - "Referer: http://000.pcl2.server/"

  - name: Minecraft 更新摘要
    url: https://raw.gitcode.com/ENC_Euphony/PCL-AI-Summary-HomePage/raw/master/Custom.xaml
    headers: 
      - "User-Agent: PCL2/0.0.0.0 Mozilla/5.0 AppleWebKit/537.36 Chrome/63.0.3239.132 Safari/537.36"
      - "Referer: http://000.pcl2.server/"

  - name: 今日新闻热点
    url: https://pcl.wyc-w.top/index.xaml
    headers: 
      - "User-Agent: PCL2/0.0.0.0 Mozilla/5.0 AppleWebKit/537.36 Chrome/63.0.3239.132 Safari/537.36"
      - "Referer: http://000.pcl2.server/"

  - name: Minecraft 芝士站
    url: https://www.xxag.top/mkss
    headers: 
      - "User-Agent: PCL2/0.0.0.0 Mozilla/5.0 AppleWebKit/537.36 Chrome/63.0.3239.132 Safari/537.36"
      - "Referer: http://000.pcl2.server/"

  - name: 整合包推荐引擎
    url: https://qawsedrftgyhujiko.fun/pcl2/Custom.xaml
    headers: 
      - "User-Agent: PCL2/0.0.0.0 Mozilla/5.0 AppleWebKit/537.36 Chrome/63.0.3239.132 Safari/537.36"
      - "Referer: http://000.pcl2.server/"
      

status-website:
  baseUrl: /PCL-Homepage-Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
